# Generated by Django 2.1.5 on 2019-02-04 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=140)),
                ('email', models.CharField(max_length=140)),
                ('age', models.PositiveIntegerField(max_length=2, validators=[django.core.validators.MaxValueValidator(70)])),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
