# Generated by Django 2.1.5 on 2019-02-04 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(70)]),
        ),
    ]
