# Generated by Django 2.1.5 on 2019-02-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190204_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='quest1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='submission',
            name='quest2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='submission',
            name='quest3',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='submission',
            name='quest4',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='submission',
            name='quest5',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='submission',
            name='quest6',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='submission',
            name='quest7',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='submission',
            name='quest8',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='submission',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
