# Generated by Django 2.1.5 on 2019-02-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190204_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
