# Generated by Django 2.1.5 on 2019-02-05 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190204_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='age',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(70)]),
        ),
    ]
